### ISSUE TITLE
RSS 订阅失败。原因: 网络许可 API 无法处理请求，因为协议未知

### ISSUE THREAD

**Issue by tomyang001** [miniers/qb-web#1]
尝试添加rss订阅（ https://rsshub.app/dsndsht23/yzymyc ）时，出现以下错误
“RSS 订阅失败。原因: 网络许可 API 无法处理请求，因为协议未知”
是否缺失https的支持？

**Comment by miniers** [comment]
<img width="758" alt="22" src="https://user-images.githubusercontent.com/2039910/63835890-001cf880-c9ab-11e9-9dd8-e099e2414933.png">
没问题试过了
