### ISSUE TITLE
换上后乱码

### ISSUE THREAD

**Issue by ljcbaby** [miniers/qb-web#15]
换上后乱码，显示“涓嶅彲鎺ュ彈鐨勬枃浠剁被鍨嬶紝鍙厑璁镐娇鐢ㄥ父瑙勬枃浠躲€�”

另外切换webui会导致自定义tracker丢失

**Comment by edisonseven** [comment]
> 换上后乱码，显示“涓嶅彲鎺ュ弹镄勬枃浠剁被鍨嬶纴鍙厑璁镐娇娇鐢ㄥ父瑙勬枃浠躲€”。
> 
> 另外切换webui会导致自定义tracker丢失

把文件路径填完整就好了，我一开始填/config/web也是这样，后来改/opt/etc/qBittorrent_entware/config/web就好了

**Comment by ljcbaby** [comment]
我是Docker版的原版qb，使用的是绝对路径




------------------&nbsp;Original&nbsp;------------------

**Comment by ljcbaby** [comment]
找到原因了。。。。。。
斜杠打反了
。。。。。。
