### ISSUE TITLE
刚开始时能用。。。等过了一段时间打开，就会出现乱码，无法访问

### ISSUE THREAD

**Issue by LianXia233** [miniers/qb-web#4]
刚开始时能用。。。等过了一段时间打开，就会出现乱码，无法访问。

**Comment by miniers** [comment]
无法重现，没法解决

**Comment by Aniverse** [comment]
我是从一切换到 alt webui 就直接乱码，没正常过……

Ubuntu 18.04
qbt 4.1.6 源码编译，依赖除了 libtorrent 外都是 apt 安装的
使用的是 qbittorrent-nox，外网访问
