### ISSUE TITLE
需求，希望能新增原版的一些操作方式

### ISSUE THREAD

**Issue by ted423** [miniers/qb-web#6]
比方右键对单个种子的操作，点击后查看具体的tracker信息以及peer信息

**Comment by ted423** [comment]
唔，还有搜索

**Comment by ted423** [comment]
默认标题似乎会全显示，建议还是可以拖动的。
因为有个别资源标题会特别长

**Comment by miniers** [comment]
第一条已经有了，搜索我自己短期没需求，有时间了可能会加，最后一条不会改，我觉得现在这样挺好
